# Generated by Django 5.2.7 on 2025-11-03 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('guest_names', models.TextField(help_text='Имена гостей для отображения на сайте (например: "Иван Иванов" или "Иван и Мария Ивановы")', verbose_name='Имена гостей')),
                ('is_plural', models.BooleanField(default=False, help_text='Отметьте, если приглашение для нескольких человек', verbose_name='Множественное число')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
    ]
