# Generated by Django 5.2.7 on 2025-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('neutral', 'Нейтральное/Общее')], default='neutral', help_text='Выберите пол для персонализации текста приглашения', max_length=10, verbose_name='Пол'),
        ),
    ]
